# .github/workflows/ci-template.yml
name: Reusable Maven CI Workflow

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: ${{ inputs.java-version }}

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: petclinic-${{ inputs.environment }}
          path: target/*.jar
